# Site settings
title: Darshil Shah
description: Darshil Shah
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Darshil Shah
user_description: 3B Engineering Student @ uWaterloo
user_title: 3B Engineering Student @ uWaterloo
email: dr5shah@uwaterloo.ca
twitter_username: lorem_ipsum
github_username:  DarshilShah-12
gplus_username:  lorem_ipsum
disqus_username: disqus_vsUMaWjaMi
leetcode_username: WhatsDerivative
codechef_username: whatsderivativ
codeforces_username: WhatsDerivative
chesscom_username: WhatsDerivative

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about
  - title: Resume
    url: "/Darshil Shah Resume.pdf"

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
